### ISSUE TITLE
V2 careers.mozilla.org - Benefits page

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#466]
## Description

Build the new benefits page in careers site to provide information and proof points of how/why it's good to work at Mozilla

Timeline - 
- Prioritization list  - TBD
- Copy first draft - TBD
- Wireframe w. lorem ipsum - TBD
-  Stakeholder QA of design w. copy - TBD
- Incorporate feedback to design and copy - TBD
- Coded page on demo - TBD
- Stakeholder QA of coded page on demo - TBD
- Code review - TBD
- Page launch - TBD

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Top nav reads “Benefits”
- [x] The page features a list of benefits (see bullets near bottom first page in [this 1-pager](https://docs.google.com/document/d/13auUaCphCf7McYqZllxsfOk-CzxtTrWYf_gJeoNoyOk/edit))
- [x] Link to Glassdoor logo at/near footer 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] ---

#### Tasks
- [x] Copy including metadata (title and description) - Rob/Natalie
- [x] UI/Design (accounting for A11y accessibility) - Cristina
- [x] Code - External
- [x] Analytics Review/QA - TBD
- [x] Code Review (id resource on Websites Team)

**Comment by dianel** [comment]
good references per Nina:

Apple https://www.apple.com/jobs/us/teams/corporate-functions.html
Spotify: I LOVE Spotify's jobs categories section - https://www.spotifyjobs.com/job-categories/
Netapp has some good ideas, too.  - https://www.netapp.com/us/careers/index.aspx

**Comment by ccooper** [comment]
@dianel This is marked as P1, but hasn't been touched in >1 year. Do we still want this?

If so, who is responsible for getting us copy?

**Comment by mostlygeek** [comment]
This is blocked waiting for new CMS work.

**Comment by mostlygeek** [comment]
We can backlog this because we're not ready to make this page yet.  Let's put this at the bottom of the ToDo list.
