### ISSUE TITLE
V2 careers.mozilla.org - Internships page

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#467]
## Description

Build the Internship page in time to catch interns in season.

[Copy doc](https://docs.google.com/document/d/13uGLRT1Fg8dbYVpxfBYolj_hTc32LnTbv4aECaPdFLo/edit)

[Miro board](https://miro.com/app/board/o9J_kw3dXVw=/?moveToWidget=3074457346955950098) - The one labeled final, far right, bottom.

Timeline - 
- Prioritization list EOD  - Sept 11
- Copy first draft - EOD Wednesday Sept 18
- Wireframe w. lorem ipsum - start next week, delivery target Monday 23
-  Stakeholder QA of design w. copy - out by _EOD Monday 23, due by EOD Tues Sept 24_
Agency (additional Consulted) feedback EOD Thursday Sept 26
- Incorporate feedback to design and copy - EOD Monday Sept 29
- Finalize wireframes for review by noon Tuesday Oct 1
- Stakeholder 24 hour review cycle for wireframe/design (in Miro board), start noon Tuesday Oct 1, end noon Wed Oct 2
- Coded page on demo - TBD
- Stakeholder QA of coded page on demo - TBD
- Code review - TBD
- Page launch - TBD

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Features New video from Rainer with intern presentations

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ]  --

#### Tasks
- [ ] Copy including metadata (title and description) - Rob/Natalie
- [ ] UI/Design (accounting for A11y accessibility) - MJones
- [ ] Code - JPetto
- [ ] Analytics Review/QA - TBD, target Xuan
- [ ] Code Review (id resource on Websites Team)

Note source content as follows:
[Detail on themes](https://docs.google.com/document/d/1YCiURrecZ3Iuyz-ieQXHg_42CTbI6zPBAmJXON5ZzyA/edit?usp=sharing) and layouts from the internship team.
New copy (source from [this](https://docs.google.com/document/d/14jhn8DIKAfbaPBROmo2xDjgPCCb02peVmZIoRsERp98/edit) and [this blog post](https://docs.google.com/document/d/19Ppvo797D1XzHvsS7mpFJsJqmTb_-1aG9XMfSO9MrDo/edit))

**Comment by ejregithub** [comment]
![DESKTOP - Internships_v5_20191024](https://user-images.githubusercontent.com/20547886/68334023-9bf37080-008e-11ea-95e9-f5cc9a241f80.jpg)
